config/routes.rb
ConcreteTest::Application.routes.draw do
  root to: 'shots#index'
  resources :shots, only: [:index, :show]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  respond_to :html
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  before_filter :api_instance
  caches_page :show

  def index
    @shots = @dribble_api.all_cached params[:page]
  end

  def show
    @shot = @dribble_api.find_cached params[:id]
  end

  private
  def api_instance
    @dribble_api = DribbleApi.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def next_page(shot)
    link_to 'Next', shots_path(anchor: "nextpage", page: shot['page'].to_i + 1), id: "shot#{shot['id']}" if has_next_page?(shot)
  end

  def previous_page(shot)
    link_to 'Previous', shots_path(anchor: "previouspage", page: shot['page'].to_i - 1), id: "shot#{shot['id']}" if has_previous_page?(shot)
  end

  private
  def has_next_page?(shot)
    shot['page'].to_i < shot['pages'].to_i
  end

  def has_previous_page?(shot)
    shot['page'].to_i <= shot['pages'].to_i && shot['page'].to_i > 1
  end
end

app/views/layouts/_navigation.html.erb
<ul class="nav navbar-nav">
    <li>
      <%= link_to "github", "https://github.com/viniciustelesbezerra" %>
    </li>
    <li>
      <%= link_to "bitbucket", "https://bitbucket.org/viniciustelesbezezerra/" %>
    </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConcreteTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
  <body>
    <header class="navbar navbar-fixed-top">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Home", root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <%= render 'layouts/navigation' %>
          </ul>
        </div>
      </div>
    </nav>
    </header>

      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/shots/_collection.html.erb
<%= link_to image_tag(shot['image_url'], class: 'img-responsive', height: 250, width: 250), shot_path(shot['id']) %>
<p id="shot<%=shot['id']%>">
  <%= link_to shot['title'], shot_path(shot['id']), id: "shot#{shot['id']}" %>
</p>
<p id="shot">
  <span class="glyphicon glyphicon-eye-open"></span>
  <%= shot['views_count'] %>
</p>

app/views/shots/_shot.html.erb
<div id="shot-section" class="col-md-4">
  <%= render partial: 'shots/collection', locals: {shot: shot} %>
</div>

app/views/shots/index.html.erb
<% if @shots.empty? %>
  <p id='noshots'>There are no shots at this moment</p>
<% else %>
  <div class="row">
    <%= render partial: 'shots/shot', collection: @shots['shots'] %>
  </div>
  <hr />
  <ul class="pager">
    <li><%= previous_page @shots %></li>
    <li><%= next_page @shots %></li>
  </ul>
<% end %>

app/views/shots/show.html.erb
<% if @shot.blank? %>
  <p id='noshot'>This shot could not be found</p>
<% else %>
  <div class="row">
    <div id="shot-section">
      <%= render partial: 'shots/collection', locals: {shot: @shot} %>
      <div id="player">
        <p><%= link_to image_tag(@shot['player']['avatar_url'], class: 'img-responsive', width: 50, height: 50), @shot['player']['url'] %></p>
        <p><%= link_to @shot['player']['name'], @shot['player']['url'] %></p>
      </div>
      <p><%= @shot['description'].html_safe %></p>
    </div>
  </div>
<% end %>